name: Cypress Tests

on:
  push:
    branches:
      - main
      - dev
      - vue-conf-23-all-fixed
  pull_request:
    branches:
      - main
      - dev

jobs:

  cypress-run-e2e:

    name: Run End-to-End Tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.9
        with:
          # Specify Browser since container image is compile with Firefox
          browser: chrome
          start: npm run serve
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true 
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  cypress-run-component:

    name: Run Component Tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.9
        with:
          # Specify Browser since container image is compile with Firefox
          browser: chrome
          component: true
          record: true
          parallel: true 
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}